// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5sEXiektIjqidfUJA4VA0KQnQj9nzkGg',
    appId: '1:752072924264:web:222de2d2c2ffceff9c2fdd',
    messagingSenderId: '752072924264',
    projectId: 'ecommerce-manage-project-0001',
    authDomain: 'ecommerce-manage-project-0001.firebaseapp.com',
    storageBucket: 'ecommerce-manage-project-0001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHhs1YbTIWcXB_s1zggMpSkBEpMe6qmds',
    appId: '1:752072924264:android:b73551b52192bef19c2fdd',
    messagingSenderId: '752072924264',
    projectId: 'ecommerce-manage-project-0001',
    storageBucket: 'ecommerce-manage-project-0001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD09hSgDUKQEzDX-6d722Eu4jRHoFO8LI',
    appId: '1:752072924264:ios:7cd43d9203f02de89c2fdd',
    messagingSenderId: '752072924264',
    projectId: 'ecommerce-manage-project-0001',
    storageBucket: 'ecommerce-manage-project-0001.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceCraftyBayLive',
  );
}
